### PR TITLE
Added special properties that can be used in yaml but won't be serialized to Json

### PR DESCRIPTION
**Pull request by erndob**
If a top level property name starts with "x-yarm", it won't be serialized to json.
The ToJson extension method accepts a boolean argument, to turn off the skipping. This lets you change the behavior at runtime. Maybe it could be opt-out on demand, through a flag in YARM-CLI.

What this let's you do. 
Imagine this yaml:
```
x-yarm-storage-auth: &storageAuth
    type: ManagedServiceIdentity
    audience: https://storage.azure.com/
x-yarm-management-auth: &managementAuth
    type: ManagedServiceIdentity
    audience: https://management .azure.com/
{...stuff...now we are defining logic app actions...}
actions:
    storageAccountHttpRequest:
        type: Http
        inputs:
           authentication: *storageAuth
           uri: whatever
           method: post
    managementAccountHttpRequest:
        type: Http
        inputs:
           authentication: *managemnetAuth
           uri: whatever
           method: post
``` 

Essentially, when using anchors in yaml, you are able to create a custom object to define just as an anchor, and then use it later on. The custom object itself won't be serialized to json.
Without this, you muse initialize anchor where you actually use it for the first time, so your anchor definitions are all over the place. With this it's nicely defined at the top.

Obviously anchors themselves are better with this https://github.com/TeamYARM/YARM-Converter/pull/1 , but this PR makes it better too.

### CODE REVIEW

**Comment by erndob** [comment]
ping

**Comment by justinyoo** [comment]
Woops. Please give me some more time. I've got other priorities (*sob*)

**Comment by justinyoo** [comment]
@erndob I've merged #1 then this starts conflicts. Would you be able to sort this out, please?

**Comment by erndob** [comment]
Done. Also caught an issue with NET461 using older version of the json serializer. All good now. 👌

**Comment by justinyoo** [comment]
@erndob Merged! Again, thanks for your contribution!

**Comment by justinyoo** [comment]
This has now been included v0.2.0: https://www.nuget.org/packages/Yarm.Converters/0.2.0

**Pull request merged**
